import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'todo-input',
  template: `
    <input [value]="generateTitle()" id="my-input">
    <button>Save</button>
    <p>The title is: {{ title }}</p>
  `,
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {
  // I commented the line below because of tslint warning: "Type string trivially inferred from a string literal, remove type annotation"
  // title: string = 'my title';
  title = 'my title';

  constructor() {
    this.title = 'hello world';
    // this.changeTitle('I love angular');
  }

  changeTitle(newTitle: string): string {
    this.title = newTitle;
    return this.title;
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  ngOnInit() {
    setTimeout(() => {
      this.title = 'This is not the title you are looking for';
    }, 3000);
  }

}
